  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Dive &amp; Green</a>
        </div>
<!--
        <div class="collapse navbar-collapse">
            <ul class="nav">
<li class="active"><a href="/en/index.html">Home</a></li>
<li><a href="/en/capur.html">Capurgana</a></li>
<li><a href="/en/courses.html">Courses</a></li>
<li><a href="/en/services.html">Services</a></li>
<li><a href="/en/tips.html">Tips</a></li>
          </ul>
        </div>
-->
<!--/.nav-collapse -->
      </div>
    </div>

