<div class="navbar navbar-default navbar-fixed-top" role="navigation"><div class="container"><div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"/><span class="icon-bar"/><span class="icon-bar"/></button><a class="navbar-brand" href="/es/">Dive &amp; Green</a></div><div class="navbar-collapse collapse"><ul class="nav navbar-nav">
  <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Dive &amp; Green<span class="caret"/></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/en/dive-and-green/">Dive &amp; Green</a></li>
    <li><a href="/en/dive-and-green/dive-green.html">Quienes Somos</a><br/>&lt;!--</li>
    <li><a href="/en/dive-and-green/">Staff de Dive &amp; Green*</a></li>
    <li>Ventajas de bucear con Dive &amp; Green</li>
    <li><a href="/en/dive-and-green/">Proyectos de Investigación*</a><br/> --&gt;</li>
  </ul></li>
  <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Capurganá<span class="caret"/></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/en/capurgana/capurgana-information.html">Capurganá Información General</a></li>
    <li><a href="/en/capurgana/travel-to.html">Travel to</a><br/>&lt;!--</li>
    <li><a href="/en/capurgana/activities.html">Activities*</a><br/>--&gt;</li>
    <li><a href="/en/capurgana/que-traer.html">What to take</a></li>
    <li><a href="/en/capurgana/hotels.html">Hotels</a></li>
  </ul></li>
  <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Diving in the Caribbean<span class="caret"/></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/en/diving-capurgana-caribbean-colombia/diving-capurgana.html">Buceo en Capurganá</a></li>
    <li><a href="/en/diving-capurgana-caribbean-colombia/dive-sites.html">Sitios de buceo</a><br/>&lt;!--</li>
    <li><a href="/en/diving-capurgana-caribbean-colombia/videos.html">Videos*</a></li>
    <li><a href="/en/diving-capurgana-caribbean-colombia/fotos.html">Fotos*</a><br/>--&gt;</li>
  </ul></li>
  <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses<span class="caret"/></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/en/courses/">Courses</a></li>
    <li><a href="/en/courses/discover-scuba-diving.html">Discover Scuba Diving</a></li>
    <li><a href="/en/courses/padi-open-water-diver.html">Open Water Diver</a></li>
    <li><a href="/en/courses/padi-scuba-review.html">Scuba Review</a></li>
    <li><a href="/en/courses/padi-scuba-diver.html">Scuba Diver</a></li>
    <li><a href="/en/courses/padi-advanced-open-water-diver.html">Advanced Open Water Diver</a></li>
    <li><a href="/en/courses/padi-rescue-diver.html">Rescue Diver</a></li>
    <li><a href="/en/courses/padi-dive-master.html">Dive Master</a></li>
    <li><a href="/en/courses/padi-especialidades.html">Specialities</a></li>
  </ul></li>
  <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Services<span class="caret"/></a>
  <ul class="dropdown-menu" role="menu">
    <li><a href="/en/services/fun-dive.html">Fun Dive</a></li>
    <li><a href="/en/services/night-dive.html">Night Dive</a></li>
    <li><a href="/en/services/plans.html">Plans</a></li>
    <li><a href="/en/services/snorkelling.html">Snorkelling</a></li>
    <li><a href="/en/services/other-services.html">Other Services</a></li>
  </ul></li>
  <li class="dropdown">Contact a Dive &amp; Green
  <ul class="dropdown-menu" role="menu">
    <li>Email</li>
    <li>Skype</li>
    <li>Twitter</li>
    <li>Facebook</li>
    <li>Youtube</li>
    <li>Google+</li>
    <li>Orkut</li>
  </ul></li>
</ul></div></div></div>