<div class="navbar navbar-default navbar-fixed-top" role="navigation"><div class="container"><div class="navbar-header"><button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"/><span class="icon-bar"/><span class="icon-bar"/></button><a class="navbar-brand" href="/es/">Dive &amp; Green</a></div><div class="navbar-collapse collapse"><ul class="nav navbar-nav">
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Dive &amp; Green<span class="caret"/></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/es/dive-and-green/">Dive &amp; Green</a></li>
<li><a href="/es/dive-and-green/dive-green.html">Quienes Somos</a> </li>
</ul></li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Capurganá<span class="caret"/></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/es/capurgana/capurgana-informacion.html">Capurganá Información General</a></li>
<li><a href="/es/capurgana/como-llegar.html">Como Llegar</a> </li>
<li><a href="/es/capurgana/que-traer.html">Que Traer</a></li>
<li><a href="/es/capurgana/alojamiento.html">Donde Quedarse</a></li>
</ul></li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Buceo en el Caribe<span class="caret"/></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/es/buceo-capurgana-caribe-colombia/buceo-capurgana.html">Buceo en Capurganá</a></li>
<li><a href="/es/buceo-capurgana-caribe-colombia/sitios.html">Sitios de buceo</a> </li>
</ul></li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Cursos<span class="caret"/></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/es/cursos/">Cursos</a></li>
<li><a href="/es/cursos/discover-scuba-diving.html">Discover Scuba Diving</a></li>
<li><a href="/es/cursos/padi-open-water-diver.html">Open Water Diver</a></li>
<li><a href="/es/cursos/padi-scuba-review.html">Scuba Review</a></li>
<li><a href="/es/cursos/padi-scuba-diver.html">Scuba Diver</a></li>
<li><a href="/es/cursos/padi-advanced-open-water-diver.html">Advanced Open Water Diver</a></li>
<li><a href="/es/cursos/padi-rescue-diver.html">Rescue Diver</a></li>
<li><a href="/es/cursos/padi-dive-master.html">Dive Master</a></li>
<li><a href="/es/cursos/padi-especialidades.html">Especialidades</a></li>
</ul></li>
<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Otros Servicios<span class="caret"/></a>
<ul class="dropdown-menu" role="menu">
<li><a href="/es/servicios/fun-dive.html">Fun Dive</a></li>
<li><a href="/es/servicios/night-dive.html">Night Dive</a></li>
<li><a href="/es/servicios/planes.html">Planes</a></li>
<li><a href="/es/servicios/snorkelling.html">Snorkelling</a></li>
<li><a href="/es/servicios/otros-servicios.html">Otros Servicios</a></li>
</ul></li>
<li class="dropdown">Contactar a Dive &amp; Green
<ul class="dropdown-menu" role="menu">
<li>Email</li>
<li>Skype</li>
<li>Twitter</li>
<li>Facebook</li>
<li>Youtube</li>
<li>Google+</li>
<li>Orkut</li>
</ul></li>
</ul></div></div></div>
